<?php

/* @noinspection ALL */
// @formatter:off
// phpcs:ignoreFile

namespace PHPSTORM_META {
    expectedArguments(
        \NormanHuth\HelloFreshScraper\Models\Allergen::getAttribute(),
        0,
        'iconPath',
        'id',
        'name',
        'slug',
        'tracesOf',
        'triggersTracesOf',
        'type',
    );
    expectedArguments(
        \NormanHuth\HelloFreshScraper\Models\Category::getAttribute(),
        0,
        'id',
        'name',
        'slug',
        'type',
    );
    expectedArguments(
        \NormanHuth\HelloFreshScraper\Models\Cuisine::getAttribute(),
        0,
        'iconLink',
        'iconPath',
        'id',
        'name',
        'slug',
        'type',
        'usage',
    );
    expectedArguments(
        \NormanHuth\HelloFreshScraper\Models\Family::getAttribute(),
        0,
        'createdAt',
        'description',
        'iconLink',
        'iconPath',
        'id',
        'name',
        'priority',
        'slug',
        'type',
        'updatedAt',
        'usageByCountry',
        'uuid',
    );
    expectedArguments(
        \NormanHuth\HelloFreshScraper\Models\Ingredient::getAttribute(),
        0,
        'country',
        'description',
        'hasDuplicatedName',
        'id',
        'imageLink',
        'imagePath',
        'internalName',
        'name',
        'shipped',
        'slug',
        'type',
        'usage',
        'uuid',
    );
    expectedArguments(
        \NormanHuth\HelloFreshScraper\Models\Label::getAttribute(),
        0,
        'backgroundColor',
        'displayLabel',
        'foregroundColor',
        'handle',
        'text',
    );
    expectedArguments(
        \NormanHuth\HelloFreshScraper\Models\Nutrition::getAttribute(),
        0,
        'amount',
        'name',
        'type',
        'unit',
    );
    expectedArguments(
        \NormanHuth\HelloFreshScraper\Models\Recipe::getAttribute(),
        0,
        'active',
        'averageRating',
        'canonical',
        'canonicalLink',
        'cardLink',
        'clonedFrom',
        'comment',
        'country',
        'createdAt',
        'description',
        'descriptionHTML',
        'descriptionMarkdown',
        'difficulty',
        'favoritesCount',
        'headline',
        'id',
        'imageLink',
        'imagePath',
        'isAddon',
        'isComplete',
        'link',
        'name',
        'prepTime',
        'promotion',
        'ratingsCount',
        'seoDescription',
        'seoName',
        'servingSize',
        'slug',
        'totalTime',
        'uniqueRecipeCode',
        'updatedAt',
        'uuid',
        'videoLink',
        'websiteUrl',
    );
    expectedArguments(
        \NormanHuth\HelloFreshScraper\Models\Nutrition::getAttribute(),
        0,
        'index',
        'ingredients',
        'instructions',
        'instructionsHTML',
        'instructionsMarkdown',
        'timers',
        'utensils',
    );
    expectedArguments(
        \NormanHuth\HelloFreshScraper\Models\Tag::getAttribute(),
        0,
        'colorHandle',
        'displayLabel',
        'id',
        'name',
        'preferences',
        'slug',
        'type',
    );
    expectedArguments(
        \NormanHuth\HelloFreshScraper\Models\Utensil::getAttribute(),
        0,
        'id',
        'name',
        'type',
    );
    expectedArguments(
        \NormanHuth\HelloFreshScraper\Models\Utensil::getAttribute(),
        0,
        'ingredients',
        'YieldsItem',
    );
}
